# Generated by Django 3.2.10 on 2021-12-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'A_course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name_teacher', models.CharField(max_length=100)),
                ('id_course', models.ManyToManyField(to='ApiConnect.Course')),
            ],
            options={
                'db_table': 'A_teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name_student', models.CharField(max_length=100)),
                ('id_course', models.ManyToManyField(to='ApiConnect.Course')),
            ],
            options={
                'db_table': 'A_student',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id_sign', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiConnect.course')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiConnect.student')),
            ],
            options={
                'db_table': 'A_sign',
            },
        ),
    ]
