# Generated by Django 3.2.10 on 2021-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_teacher',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
