# Generated by Django 3.2.10 on 2021-12-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiConnect', '0002_auto_20211218_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
