# Generated by Django 3.2.10 on 2021-12-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiConnect', '0004_alter_student_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_teacher',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
