# Generated by Django 3.2.10 on 2021-12-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiConnect', '0006_auto_20211223_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_course',
            field=models.ManyToManyField(blank=True, to='ApiConnect.Course'),
        ),
    ]
