# Generated by Django 3.2.10 on 2021-12-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Z_Course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.AutoField(primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=100)),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='McyangApi.course')),
            ],
            options={
                'db_table': 'Z_Teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_ID', models.ManyToManyField(related_name='Z_Course_Student', to='McyangApi.Course')),
            ],
            options={
                'db_table': 'Z_Student',
            },
        ),
    ]
