# Generated by Django 3.2.10 on 2021-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('McyangApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('signID', models.AutoField(primary_key=True, serialize=False)),
                ('course_ID', models.IntegerField()),
                ('student_ID', models.IntegerField()),
                ('student_Name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Z_Sign',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='Course_ID',
            field=models.ManyToManyField(to='McyangApi.Course'),
        ),
    ]
