# Generated by Django 3.2.10 on 2021-12-22 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('McyangApi', '0002_auto_20211223_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
